//Company
export const ADD_COMPANY_INIT = 'ADD_COMPANY_INIT';
export const ADD_COMPANY = 'ADD_COMPANY';

export const REMOVE_COMPANY_INIT = 'REMOVE_COMPANY_INIT';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';

export const EDIT_COMPANY_INIT = 'EDIT_COMPANY_INIT';
export const EDIT_COMPANY = 'EDIT_COMPANY';

export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANY = 'GET_COMPANY';

//Competition
export const ADD_COMPETITION_INIT = 'ADD_COMPETITION_INIT';
export const ADD_COMPETITION = 'ADD_COMPETITION';

export const REMOVE_COMPETITION_INIT = 'REMOVE_COMPETITION_INIT';
export const REMOVE_COMPETITION = 'REMOVE_COMPETITION';

export const EDIT_COMPETITION_INIT = 'EDIT_COMPETITION_INIT';
export const EDIT_COMPETITION = 'EDIT_COMPETITION';

export const GET_COMPETITIONS = 'GET_COMPETITIONS';
export const GET_COMPETITION = 'GET_COMPETITION';

//Category
export const ADD_CATEGORY_INIT = 'ADD_CATEGORY_INIT';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const REMOVE_CATEGORY_INIT = 'REMOVE_CATEGORY_INIT';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

export const EDIT_CATEGORY_INIT = 'EDIT_CATEGORY_INIT';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';

//Contestant
export const ADD_CONTESTANT_INIT = 'ADD_CONTESTANT_INIT';
export const ADD_CONTESTANT = 'ADD_CONTESTANT';

export const REMOVE_CONTESTANT_INIT = 'REMOVE_CONTESTANT_INIT';
export const REMOVE_CONTESTANT = 'REMOVE_CONTESTANT';

export const EDIT_CONTESTANT_INIT = 'EDIT_CONTESTANT_INIT';
export const EDIT_CONTESTANT = 'EDIT_CONTESTANT';

export const GET_CONTESTANT_INIT = 'GET_CONTESTANT_INIT';
export const GET_CONTESTANT = 'GET_CONTESTANT';

export const VOTE_CONTESTANT = 'VOTE_CONTESTANT';


//User
export const LOGIN_INIT = 'LOGIN_INIT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_INIT = 'SIGNUP_INIT';
export const SIGNUP = 'SIGNUP';
export const CHECK_USER_AVAILABLE = 'CHECK_USER_AVAILABLE';